config/routes.rb
Rails.application.routes.draw do
  resources :entries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  root to: "entries#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_path, status: :see_other, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.expect(entry: [ :meal_type, :calories, :proteins, :carbohydrates, :fats ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Meal type:</strong>
    <%= entry.meal_type %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= entry.calories %>
  </p>

  <p>
    <strong>Proteins:</strong>
    <%= entry.proteins %>
  </p>

  <p>
    <strong>Carbohydrates:</strong>
    <%= entry.carbohydrates %>
  </p>

  <p>
    <strong>Fats:</strong>
    <%= entry.fats %>
  </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
      <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      <div class="message-body">
      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: "label" %>
    <%= form.number_field :proteins, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">Editing entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog &ndash; <%= DateTime.now.strftime("%B %e, %Y") %>
<% end %>
<div class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
          <%= entry.meal_type %>
          </p>
        </header>
      <div class="card-content">
        <div class="content">
          <p><span class="has-text-weight-bold"><%= entry.calories %></span> Calories</p>
          <p><span class="has-text-weight-bold"><%= entry.proteins %></span> Grams of Protein</p>
          <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> Grams of Carbohydrates</p>
          <p><span class="has-text-weight-bold"><%= entry.fats %></span> Grams of Fat</p>
          <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
        </div>
      </div>
      <div class="card-footer">
        <%= link_to "Show", entry, class: "card-footer-item" %>
        <%= link_to "Edit", edit_entry_path(entry), class: "card-footer-item" %>
        <%= link_to "Destroy", entry, method: :delete, data: {confirm: "Are you sure"}, class: "card-footer-item" %>
      </div>
    </div>
    </div>
  <% end %>
</div>

<%= link_to "New entry", new_entry_path %>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">New entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<%= render @entry %>

<div>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= link_to "Back to entries", entries_path %>
  <%= button_to 'Delete', entry_path(@entry), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: 'button is-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ruby On Rails Tutorial" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <% if notice.present? %>
      <div class="notification is-link is-light"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
      <div class="notification is-danger is-light"><% alert %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <svg width="20" height="20" fill="currentColor" class="bi bi-fork-knife" viewBox="0 0 16 16"><path d="M13 .5c0-.276-.226-.506-.498-.465-1.703.257-2.94 2.012-3 8.462a.5.5 0 0 0 .498.5c.56.01 1 .13 1 1.003v5.5a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5zM4.25 0a.25.25 0 0 1 .25.25v5.122a.128.128 0 0 0 .256.006l.233-5.14A.25.25 0 0 1 5.24 0h.522a.25.25 0 0 1 .25.238l.233 5.14a.128.128 0 0 0 .256-.006V.25A.25.25 0 0 1 6.75 0h.29a.5.5 0 0 1 .498.458l.423 5.07a1.69 1.69 0 0 1-1.059 1.711l-.053.022a.92.92 0 0 0-.58.884L6.47 15a.971.971 0 1 1-1.942 0l.202-6.855a.92.92 0 0 0-.58-.884l-.053-.022a1.69 1.69 0 0 1-1.059-1.712L3.462.458A.5.5 0 0 1 3.96 0z" /></svg>
            <span class="has-text-weight-bold is-size-4 ml-4">Foodlog</span>
          <% end %>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <%= link_to "Create new entry", new_entry_path, class: "button is-success" %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
      <% if content_for(:title) %>
        <%= yield :title %>
      <% else %>
        Foodlog
      <% end %>
      </p>
    </div>
  </div>

</section>